### ISSUE TITLE
ระบบไอเทม

### ISSUE THREAD

**Issue by Th3than** [ExtraStudent101/Scratch-Project#12]

**Comment by ExtraStudent101** [comment]
ทำไอค่อนไอเทม(ชั่วคราว) เสียงหลังกดไอเทม และระบบคูลดาวน์ เสร็จเรียบร้อย ยังต้องปรับการทำงานของแต่ละชิ้นให้สมบูรณ์ขึ้นอีก

**Comment by ExtraStudent101** [comment]
เพิ่มระบบโอกาสการกดติดของไอเทมเรียบร้อย

**Comment by ExtraStudent101** [comment]
https://scratch.mit.edu/projects/731424717/editor ตอนนี้ยังไม่สามารถซิ้งระบบไอเทมให้สอดคล้องกับระบบของผีได้
