### ISSUE TITLE
ระบบค่าแข็งแรงของห้อง

### ISSUE THREAD

**Issue by Th3than** [ExtraStudent101/Scratch-Project#13]

**Comment by apwjir** [comment]
ทำระบบค่าความแข็งแรงของห้องแต่ละห้อง และตึกเสร็จเรียบร้อย เหลือระบบการซ่อมห้องที่เวลาซ่อมเสร็จจะให้โผล่ออกมาที่ห้องไหน

**Comment by apwjir** [comment]
https://scratch.mit.edu/projects/730138742/editor
ปัญหาคือ บล็อคคำสั่งที่สร้างไม่ยอมทำงาน
